#define _POSIX_C_SOURCE 200809L

#include "commands.h"
#include "../util.h"
#include "../relay.h"
#include "../solana_rpc.h"

#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>

void cmd_opts_init(cmd_opts_t *o)
{
    memset(o, 0, sizeof(*o));
    o->relay_url = VIDX_DEFAULT_RELAY;
    o->rpc_url = VIDX_DEFAULT_RPC_MAINNET;
    o->cluster = "mainnet";
    o->wait_seconds = 600;  // 10 min
    o->tls_strict = 1;
}

static int mkdir_p(const char *path, mode_t mode)
{
    char tmp[1024];
    snprintf(tmp, sizeof(tmp), "%s", path);
    size_t len = strlen(tmp);
    if (len == 0) return -1;
    if (tmp[len-1] == '/') tmp[len-1] = '\0';
    for (char *p = tmp + 1; *p; p++) {
        if (*p == '/') {
            *p = '\0';
            if (mkdir(tmp, mode) != 0 && errno != EEXIST) return -1;
            *p = '/';
        }
    }
    if (mkdir(tmp, mode) != 0 && errno != EEXIST) return -1;
    return 0;
}

int cmd_init(const cmd_opts_t *o)
{
    const char *home = getenv("HOME");
    if (!home) {
        log_error("HOME is not set");
        return VIDX_ERR_USAGE;
    }
    char dir[1024];
    snprintf(dir, sizeof(dir), "%s/.vid-transfer", home);
    if (mkdir_p(dir, 0700) != 0) {
        log_error("mkdir %s: %s", dir, strerror(errno));
        return VIDX_ERR_IO;
    }
    char cfg_path[1100];
    snprintf(cfg_path, sizeof(cfg_path), "%s/config.toml", dir);

    struct stat st;
    if (stat(cfg_path, &st) == 0) {
        log_warn("config already exists at %s — leaving in place.", cfg_path);
        return 0;
    }

    char body[2048];
    int n = snprintf(body, sizeof(body),
        "# vid-transfer config — generated by `vid-transfer init`\n"
        "# Override at the command line with --relay / --rpc / --cluster.\n"
        "\n"
        "[relay]\n"
        "url = \"%s\"\n"
        "tls_strict = true\n"
        "\n"
        "[solana]\n"
        "cluster = \"%s\"\n"
        "rpc_url = \"%s\"\n"
        "\n"
        "[transfer]\n"
        "wait_seconds = 600\n"
        "include_tower = true\n",
        o->relay_url, o->cluster, o->rpc_url);
    if (n < 0) return VIDX_ERR_INTERNAL;

    vidx_status_t s = write_file_atomic(cfg_path, (uint8_t *)body, (size_t)n, 0600);
    if (s != VIDX_OK) return s;

    log_ok("wrote %s", cfg_path);
    log_info("Edit the file to point at your own relay if you self-host.");
    return 0;
}
